### ISSUE TITLE
Could not detect input event

### ISSUE THREAD

**Issue by B4rabbas** [namark/xboxdrv-config#1]
Hello,
When I try to start the script, I follow the indications (shutdown or connect my controller) before press enter I always got this::
Could not detect input event. Please try again, or specify the event manually using the -e option.

When I use -e indication with my event (20 in my case) it dont work neither.
I have to precise the first time I've use your script it was functionnal, but not anymore...
Cheers

**Comment by namark** [comment]
Hi, that's strange... you are running the script on the same system and it doesn't work anymore? Do you get any error messages running  with the **-e** option, or does it just stop working at some point?

A couple of tips that might help out:
1. try running the script with super user privileges 
2. make sure you have **evtest** installed
3. for the **-e** option make sure to specify the full path to the event "file", for example: 
`./xboxdrv-config.sh -e /dev/input/event20`

If none of this things help try running **evtest** by itself with super user, and it should present you with a list of all the connected input devices. Select the one you need and see if pressing anything registers with **evtest**, and paste the a sample output here. It could be that the script can't parse what **evtest** outputs in your case and I might be able to update it to work properly.

**Comment by B4rabbas** [comment]
Sorry for the late response.

Evtest just don't show the device anymore, very strange. I'll try to reproduce it.
